<?xml version="1.0" encoding="utf-8"?><Database Name="bancoRSS" Class="modeloRssDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\App_Data\bancoRSS.mdf;Integrated Security=True" SettingsObjectName="RSS_1.Properties.Settings" SettingsPropertyName="bancoRSSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Categoria" Member="Categoria">
    <Type Name="Categoria">
      <Column Name="cat_codigo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cat_descricao" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Categoria_Feed" Member="Feed" ThisKey="cat_codigo" OtherKey="cat_codigo" Type="Feed" />
    </Type>
  </Table>
  <Table Name="dbo.Regra" Member="Regra">
    <Type Name="Regra">
      <Column Name="regra_codigo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="regra_chaves" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="regra_ativo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="regra_tipo" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Feed" Member="Feed">
    <Type Name="Feed">
      <Column Name="feed_codigo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="feed_descricao" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="feed_qt_nao_lidos" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cat_codigo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Feed_Item" Member="Item" ThisKey="feed_codigo" OtherKey="feed_codigo" Type="Item" />
      <Association Name="Categoria_Feed" Member="Categoria" ThisKey="cat_codigo" OtherKey="cat_codigo" Type="Categoria" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Item" Member="Item">
    <Type Name="Item">
      <Column Name="item_codigo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="item_link" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="item_titulo" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="item_lido" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="item_conteudo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="item_dthr" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="feed_codigo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Feed_Item" Member="Feed" ThisKey="feed_codigo" OtherKey="feed_codigo" Type="Feed" IsForeignKey="true" />
    </Type>
  </Table>
</Database>